// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdorldvsqgcnftplqeav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkb3JsZHZzcWdjbmZ0cGxxZWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODQ2OTcsImV4cCI6MjA2MDY2MDY5N30.2_PFcwJiImNtRlPzGU1YReUZX6LWMtVawffRCetyueA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);